updated install brew packages script

diff --git a/chezmoi/.chezmoiscripts/run_once_before_20-install-prerequisites-common.sh.tmpl b/chezmoi/.chezmoiscripts/run_once_before_20-install-prerequisites-common.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_once_before_20-install-prerequisites-common.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_once_before_20-install-prerequisites-common.sh.tmpl
@@ -8,28 +8,26 @@
 true || source ../.chezmoitemplates/scripts-library
 true || source ../.chezmoitemplates/homebrew-library
 
-if brew --version &>/dev/null; then
+readonly wanted_packages=(
+  age
+)
+missing_packages=()
 
-  readonly wanted_packages=(
-    age
-  )
-  missing_packages=()
+for package in "${wanted_packages[@]}"; do
+  if ! is_brew_package_installed "${package}"; then
+    missing_packages+=("${package}")
+  fi
+done
 
-  for package in "${wanted_packages[@]}"; do
-    if ! is_brew_package_installed "${package}"; then
-      missing_packages+=("${package}")
-    fi
-  done
+if [[ ${#missing_packages[@]} -gt 0 ]]; then
+  log_task "Installing missing packages with brew: ${missing_packages[*]}"
 
-  if [[ ${#missing_packages[@]} -gt 0 ]]; then
-    log_task "Installing missing packages with brew: ${missing_packages[*]}"
+  brew_command=(brew)
 
-    brew_command=(brew)
-
-    # c "${brew_command[@]}" update
+  if brew --version &>/dev/null; then
+    c "${brew_command[@]}" update
     c "${brew_command[@]}" install "${missing_packages[@]}"
   fi
-
 fi
 
 # {{ end -}}
