updated gpg key management script

diff --git a/chezmoi/.chezmoiscripts/run_once_after_40-setup-keys.sh.tmpl b/chezmoi/.chezmoiscripts/run_once_after_40-setup-keys.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_once_after_40-setup-keys.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_once_after_40-setup-keys.sh.tmpl
@@ -123,19 +123,37 @@ if [ -z "${GPG_KEY_ID}" ] && [ -e "${GPG_KEY_ID_FILE}" ]; then
 fi
 # if GPG_KEY_ID is not empty, check if it is a valid key ID
 if [ -n "${GPG_KEY_ID}" ]; then
-    log_info "GPG_KEY_ID: ${GPG_KEY_ID}"
-    GPG_PRIVATE_KEY_FILE="${GNUPGHOME}/${GPG_KEY_ID}.private"
-    log_task "Checking GPG key"
-    GPG_KEY_ID=$(gpg --list-secret-keys --with-colons | grep 'sec' | grep "${GPG_KEY_ID}" | cut -d':' -f5 || echo "")
-    # {{ if .system.is_interactive }}
-    # if GPG_KEY_ID is empty and private key file exists, import it
-    if [ -z "${GPG_KEY_ID}" ] && [ -e "${GPG_PRIVATE_KEY_FILE}" ]; then
-        log_task "Importing GPG key"
-        c gpg --import "${GPG_PRIVATE_KEY_FILE}"
+    GPG_PRIVATE_KEY_FILE="${GNUPGHOME}/${GPG_KEY_ID}.key"
+    GPG_PUB_KEY_FILE="${GPG_PRIVATE_KEY_FILE}.pub"
+    log_task "Checking the GPG public key"
+    GPG_PUB_KEY_ID=$(gpg --list-keys --with-colons | grep 'pub' | grep "${GPG_KEY_ID}" | cut -d':' -f5 || echo "")
+    if [ -z "${GPG_PUB_KEY_ID}" ]; then
+        if [ -e "${GPG_PUB_KEY_FILE}" ]; then
+            log_task "Importing the GPG public key"
+            c gpg --import "${GPG_PUB_KEY_FILE}"
+        else
+            log_manual_action "GPG public key not found"
+        fi
     else
-        log_manual_action "Import GPG key"
+        log_info "GPG public key already imported"
     fi
-    # {{ end }}
+    log_task "Checking the GPG private key"
+    GPG_KEY_ID=$(gpg --list-secret-keys --with-colons | grep 'sec' | grep "${GPG_KEY_ID}" | cut -d':' -f5 || echo "")
+    # if GPG_KEY_ID is empty and private key file exists, import it
+    if [ -z "${GPG_KEY_ID}" ]; then
+        if [ -e "${GPG_PRIVATE_KEY_FILE}" ]; then
+            log_task "Importing the GPG private key"
+            # {{ if .system.is_interactive }}
+            c gpg --allow-secret-key-import --import "${GPG_PRIVATE_KEY_FILE}"
+            # {{ else }}
+            c gpg --batch --pinentry-mode=loopback --yes --passphrase "{{ .gnupg.passphrase }}" --import "${GPG_PRIVATE_KEY_FILE}"
+            # {{ end }}
+        else
+            log_info "GPG private key not found"
+        fi
+    else
+        log_info "GPG private key already imported"
+    fi
 fi
 # {{ if .gnupg.passphrase }}
 # Create a batch file
@@ -152,7 +170,6 @@ if [ -z "${GPG_KEY_ID}" ]; then
         Subkey-Type: ECDH
         Subkey-Curve: cv25519
         Name-Real: {{ .name }}
-        Name-Comment: generated by chezmoi
         Name-Email: {{ .email }}
         Expire-Date: 0
         Passphrase: {{ .gnupg.passphrase }}
@@ -162,16 +179,59 @@ if [ -z "${GPG_KEY_ID}" ]; then
 EOF
     c gpg --batch --generate-key .tmp_gpg_batch
     rm .tmp_gpg_batch
+
     GPG_KEY_ID=$(gpg --list-secret-keys --with-colons | grep 'sec' | tail -n 1 | cut -d':' -f5)
-    # Save the key ID to a file
-    echo "${GPG_KEY_ID}" > "${GPG_KEY_ID_FILE}"
+    GPG_PRIVATE_KEY_FILE="${GNUPGHOME}/${GPG_KEY_ID}.key"
+    GPG_PRIVATE_ASC_KEY_FILE="${GPG_PRIVATE_KEY_FILE}.asc"
+    GPG_PUB_KEY_FILE="${GPG_PRIVATE_KEY_FILE}.pub"
+    GPG_PUB_ASC_KEY_FILE="${GPG_PUB_KEY_FILE}.asc"
     # Save public key to a file
-    c gpg --armor --export "${GPG_KEY_ID}" > "${GNUPGHOME}/${GPG_KEY_ID}.pub"
+    log_task "Exporting GPG public key"
+    c gpg --export --armor  "${GPG_KEY_ID}" > "${GPG_PUB_ASC_KEY_FILE}"
+    c gpg --export "${GPG_KEY_ID}" > "${GPG_PUB_KEY_FILE}"
+    # Save private key to a file
+    log_task "Exporting GPG private key"
+    c gpg --batch --pinentry-mode=loopback --yes --passphrase "{{ .gnupg.passphrase }}" --export-secret-keys --armor "${GPG_KEY_ID}" > "${GPG_PRIVATE_ASC_KEY_FILE}"
+    c gpg --batch --pinentry-mode=loopback --yes --passphrase "{{ .gnupg.passphrase }}" --export-secret-keys "${GPG_KEY_ID}" > "${GPG_PRIVATE_KEY_FILE}"
 fi
+# {{ else }}
+# {{   if .system.is_interactive }}
+if [ -z "${GPG_KEY_ID}" ]; then
+    log_task "Generating GPG key"
+    c gpg --full-generate-key
+
+    GPG_KEY_ID=$(gpg --list-secret-keys --with-colons | grep 'sec' | tail -n 1 | cut -d':' -f5)
+    GPG_PRIVATE_KEY_FILE="${GNUPGHOME}/${GPG_KEY_ID}.key"
+    GPG_PRIVATE_ASC_KEY_FILE="${GPG_PRIVATE_KEY_FILE}.asc"
+    GPG_PUB_KEY_FILE="${GPG_PRIVATE_KEY_FILE}.pub"
+    GPG_PUB_ASC_KEY_FILE="${GPG_PUB_KEY_FILE}.asc"
+    # Save public key to a file
+    log_task "Exporting GPG public key"
+    c gpg --export --armor  "${GPG_KEY_ID}" > "${GPG_PUB_ASC_KEY_FILE}"
+    c gpg --export "${GPG_KEY_ID}" > "${GPG_PUB_KEY_FILE}"
+    # Save private key to a file
+    log_task "Exporting GPG private key"
+    c gpg --export-secret-keys --armor "${GPG_KEY_ID}" > "${GPG_PRIVATE_ASC_KEY_FILE}"
+    c gpg --export-secret-keys "${GPG_KEY_ID}" > "${GPG_PRIVATE_KEY_FILE}"
+fi
+# {{   else }}
+if [ -z "${GPG_KEY_ID}" ]; then
+    log_manual_action "Generate GPG key"
+fi
+# {{   end }}
 # {{ end }}
 
 log_info "GPG key ID: ${GPG_KEY_ID}"
+# Save the key ID to a file if it's different or if the file doesn't exist
+if [ ! -e "${GPG_KEY_ID_FILE}" ] || [ "${GPG_KEY_ID}" != "$(cat "${GPG_KEY_ID_FILE}")" ]; then
+    echo "${GPG_KEY_ID}" > "${GPG_KEY_ID_FILE}"
+fi
 export GPG_KEY_ID="${GPG_KEY_ID}"
+GPG_PRIVATE_KEY_FILE="${GNUPGHOME}/${GPG_KEY_ID}.key"
+GPG_PRIVATE_ASC_KEY_FILE="${GPG_PRIVATE_KEY_FILE}.asc"
+GPG_PUB_KEY_FILE="${GPG_PRIVATE_KEY_FILE}.pub"
+GPG_PUB_ASC_KEY_FILE="${GPG_PUB_KEY_FILE}.asc"
+
 # add gpg key to gitconfig
 # if [ -n "${GPG_KEY_ID}" ]; then
 #     log_task "Adding GPG key to gitconfig"
@@ -188,24 +248,22 @@ if command -v gh >/dev/null; then
         log_task "Adding SSH key to GitHub"
         c gh ssh-key add "${SSH_PUB_KEY_FILE}" --title "${USER}@${HOST} ${ALGORITHM} ${DATESTAMP}" || true
     fi
-    # if [ -f "${GPG_PUB_KEY_FILE}" ]; then
-    #     log_task "Adding GPG key to GitHub"
-    #     c gh gpg-key add "${GPG_PUB_KEY_FILE}" || true
-    # fi
+    if [ -e "${GPG_PUB_ASC_KEY_FILE}" ]; then
+        log_task "Adding GPG key to GitHub"
+        c gh gpg-key add "${GPG_PUB_ASC_KEY_FILE}" || true
+    fi
     # setup git authentication
     c gh auth setup-git
 else
     log_info "gh is not installed"
+    log_manual_action "If you want to add SSH key to GitHub for signing commits (github-cli does not support this yet), visit the following URL: "
+    log_manual_action " > https://github.com/settings/ssh/new"
+    if [ -e "${GPG_PUB_ASC_KEY_FILE}" ]; then
+        log_manual_action "If you want to add GPG key to GitHub for signing commits, run the following: "
+        log_manual_action " > gh gpg-key add ${GPG_PUB_ASC_KEY_FILE}"
+    fi
 fi
-
-log_manual_action "If you want to add SSH key to GitHub for signing commits (github-cli does not support this yet), visit the following URL: "
-log_manual_action " > https://github.com/settings/ssh/new"
-
-GPG_PUB_KEY_FILE="${GNUPGHOME}/${GPG_KEY_ID}.pub"
-if [ -e "${GPG_PUB_KEY_FILE}" ]; then
-    log_manual_action "If you want to add GPG key to GitHub for signing commits, run the following: "
-    log_manual_action " > gh gpg-key add ${GPG_PUB_KEY_FILE}"
-fi
-log_info "Done setting up SSH, AGE, and GPG keys"
 # {{ end -}}
+
+log_info "Done setting up SSH, AGE, and GPG keys"
 # {{ end -}}
